[package]
name = "rusty-gpib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.9"
thiserror = "2.0"

[build-dependencies]
bindgen = "0.71"
